### ISSUE TITLE
address payable syntax error

### ISSUE THREAD

**Issue by pizza-r0b** [juanfranblanco/vscode-solidity#117]
I believe as of solidity 0.5.0 address types need to be marked payable in order to have a transfer method. The code compiles fine, but I am getting a syntax error.

![image](https://user-images.githubusercontent.com/5282495/50564340-f1295d80-0cd8-11e9-9304-a935060c1f6f.png)

**Comment by obernardovieira** [comment]
Hi, which linter are you using? Does it support solidity 0.5.0? Are you using the right version at pragma? Like `pragma solidity ^0.5.0;`

**Comment by pizza-r0b** [comment]
Hey I'm using solhint and the pragma is correct

**Comment by pizza-r0b** [comment]
Anything on this? The false syntax error breaks the rest of the linting. If time is an issue point me in the direction of the file to edit to fix this.

**Comment by rocky** [comment]
The [default linter seems to be solium](https://github.com/juanfranblanco/vscode-solidity/blob/master/package.json#L102) 

https://www.npmjs.com/package/solium-plugin-security#list-of-rules describes how to turn on and off individual rules in a ` soliumrc.json`. 

I assume this should be enough to figure out a workaround. The steps I'd try is to see if this is a bug in solium which, by the way,  is now called ethlint. Perhaps upgrading will fix that. If it is a bug in ethlint, then I'd look at that project to see if this has been reported and what the fix is. 

Finally, I'd say that if I were wanted to delve into addressing this, I'd want the to have the full text to shortest contract that shows the problem so I could easily see the problem. Thas hasn't been given yet.

**Comment by pizza-r0b** [comment]
Hey FYI I fixed this by using solhint as the linter 👍

**Comment by juanfranblanco** [comment]
Apologies @pizza-r0b I have not had time to look at this, but I will check with the now Ethlint about this.
