### ISSUE TITLE
Error about compiler version

### ISSUE THREAD

**Issue by louneskmt** [juanfranblanco/vscode-solidity#171]
Hi!

I just want to use the latest version of the compiler, so I set the setting `"solidity.compileUsingRemoteVersion"` to `"true"`, but I still have this error in all the @openzeppelin's files :

> Source file requires different compiler version (current compiler is 0.6.4+commit.1dca32f3.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version

What can I do to fix that ? Thanks!

**Comment by juanfranblanco** [comment]
@lounes-kmt true is not an option you need to set it to "latest" or the specific version you need. 
You can also right click and change the global setting for the compiler

![image](https://user-images.githubusercontent.com/562371/78467720-628b6380-7707-11ea-8fca-5cc1605e6117.png)

this will bring the compiler options

![image](https://user-images.githubusercontent.com/562371/78467743-96ff1f80-7707-11ea-945c-e538d015ac82.png)

**Comment by lounes-kmt** [comment]
Really sorry, I made a mistake writing this issue, the setting is currently set to `latest` as expected

**Comment by juanfranblanco** [comment]
You will need to upgrade the Open Zeppelin files to the latest version or make your version a lower version.

**Comment by wighawag** [comment]
I am getting a similar issue with local setting enabled.
The problem is that the tool I am using (https://buidler.dev) install latest solc in node_modules
And vscode-solidity pick that instead of the local file I specified.

vscode-solidity should consider the settings first if there are defined/

The work around for me was to install solc at the specific version I want but that should not be necessary if vscode-solidity consider preferences settings first

**Comment by juanfranblanco** [comment]
@wighawag apologies I have just seen this, there is a setting to stop using the node_modules

**Comment by wighawag** [comment]
Cool thanks, I ll use that now
