### ISSUE TITLE
Code completion for variable declararation not working

### ISSUE THREAD

**Issue by vzts** [juanfranblanco/vscode-solidity#66]
Am I the only one who don't get auto-completion for declared variables in the same file? Manually typing all variables is really bothering. I can see there is a feature `Code completion for all contracts / libraries in the current file and all referenced imports` in README, but it doesn't seem working.

I am using VS Code 1.22.2 in macOS High Sierra 10.13.4(17E202), with the latest extension provided(0.0.40) and I'm writing with solidity v0.4.23.

**Comment by juanfranblanco** [comment]
variables on the same function have not been implemented yet. So you will get autocomplete from attributes in the current contract and methods.

**Comment by juanfranblanco** [comment]
#58 reference autocomplete improvements

**Comment by as-ajitsingh** [comment]
Hi Juan,
I am facing the same problem, for me autocomplete is not working in the current contract.
![no-autocomplete](https://user-images.githubusercontent.com/32074655/40174848-e178483a-59f3-11e8-9c9c-89464bbed404.png)

**Comment by juanfranblanco** [comment]
@as-ajitsingh are you using latest? I had the same issue as 24 is out.

**Comment by saurfang** [comment]
This is an annoying issue indeed. A quick look seems to suggest because when we incrementally type variable name, the contract enters a compilation error state thus cannot auto-complete variable names in the current scope.
I suppose we could try complete without current line if completion fails but it feels too hacky and wouldn't work for multi-line statement. The proper solution is probably use a non-validating parser instead so it returns best effort result.

If I `cmd + space` then type `y`, I get

![image](https://user-images.githubusercontent.com/4317392/42148774-59ba0d26-7d88-11e8-92c4-da6ea72d37c0.png)


but if I type `y` then `cmd + space`

![image](https://user-images.githubusercontent.com/4317392/42148785-64f73a1a-7d88-11e8-9fa1-0744ecaf75e9.png)

**Comment by juanfranblanco** [comment]
Yes, you are right, I was thinking about using the Antlr parser but still have seen issues.
